### ISSUE TITLE
NoClassDefFoundError at creating intent

### ISSUE THREAD

**Issue by elekt** [CodelightStudios/Android-Smart-Login#25]
Hey I set up the library and manifest file as explained, but at building the intent like this:

```
Intent intent = new SmartLoginBuilder().with(MainActivity.this)
        .setAppLogo(R.drawable.app_logo_circ)
        .isFacebookLoginEnabled(true).withFacebookAppId(getString(R.string.facebook_app_id))
        .isGoogleLoginEnabled(false)
        .build();
startActivityForResult(intent, SmartLoginConfig.LOGIN_REQUEST);
```

I get the following exception. It means that I have some kind of linking problem. 

```
08-26 12:24:16.044 6195-6195/com.app.appdemo.daily.developer E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: studios.codelight.smartloginlibrary.SmartLoginActivity
   at studios.codelight.smartloginlibrary.SmartLoginBuilder.build(SmartLoginBuilder.java:66)
   at com.app.appdemo.screens.main.MainActivity.onCreate(MainActivity.java:56)
   at android.app.Activity.performCreate(Activity.java:5133)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
   at android.app.ActivityThread.access$600(ActivityThread.java:153)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:5289)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:525)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
   at dalvik.system.NativeStart.main(Native Method)
```

Can you give me possible solutions?

**Comment by kalyandechiraju** [comment]
Hi @elekt Can you confirm me that you have added `compile project(':smartloginlibrary-v0.5beta')` under dependencies in your app/build.gradle file ?

**Comment by elekt** [comment]
Yes,
It seems that not having the same version of a dependency that is defined in the lib, and in my app can cause such.

**Comment by LookitheFirst** [comment]
I have the same problem

**Comment by kalyandechiraju** [comment]
@elekt @LookitheFirst The library is updated to version 1.x and also uploaded to jcenter. Check out README for more details. Project Wiki will be ready soon.
