### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by joonas123** [CodelightStudios/Android-Smart-Login#29]
When I try to sign out my superUser, application crashes. Log says that transaction is too large. Below is part of the logcat. I'm I the only one with this issue?

`09-14 11:49:37.965 7904-7904/studios.codelight.smartlogin D/Error: ERR: TOTAL BYTES WRITTEN: 28404168
09-14 11:49:37.968 7904-7904/studios.codelight.smartlogin E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 28404252)
09-14 11:49:37.968 7904-7914/studios.codelight.smartlogin I/art: Background sticky concurrent mark sweep GC freed 23(1360B) AllocSpace objects, 1(27MB) LOS objects, 2% free, 129MB/133MB, paused 5.134ms total 83.796ms
09-14 11:49:37.973 7904-7904/studios.codelight.smartlogin E/AndroidRuntime: Error reporting crash
                                                                            android.os.TransactionTooLargeException: data parcel size 28404252 bytes
                                                                                at android.os.BinderProxy.transactNative(Native Method)
                                                                                at android.os.BinderProxy.transact(Binder.java:503)
                                                                                at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
                                                                                at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)`

**Comment by kalyandechiraju** [comment]
Well @joonas123 Can you help me out in simulating it? In what situation did you get that error?

**Comment by joonas123** [comment]
Thanks for quick response. 

Problem occurs with both emulator and real device. I created a new smart user and after that I tried to show smart login. When I pressed "Show Smart Login" -button, application said that "User already logged in". If I then click Logout, the application crashes. It looks like the application is calling customUserSignout() over and over again. 

If you can't track down the bug, it might just be that my code is corrupted somehow. Unfortunately I have no time  to inspect it more thoroughly at the moment.

**Comment by kalyandechiraju** [comment]
@joonas123 anyhow am working on the next version of it without the dependency on UI. Can you hold for a few days until the updated version?

Actually, a lot of things changed in both Google and Facebook login. Due to some limitations of Google login in v1 api, I was forced to use some static references, which are very bad in the activity lifecycle scenario. So am trying to fix all those issues as well.

Thanks for trying out Smart Login.

**Comment by khuranadhruv18** [comment]
Have you gotten a fix yet?

**Comment by kalyandechiraju** [comment]
@joonas123 @khuranadhruv18  The new version (1.x) has this fix.
